/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tim_1.peternakan;

/**
 *
 * @author LENOVO
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        beliButton = new javax.swing.JButton();
        jualButton = new javax.swing.JButton();
        breedButton = new javax.swing.JButton();
        listHewanButton = new javax.swing.JButton();
        listPegawaiButton = new javax.swing.JButton();
        gajiPegawaiButton = new javax.swing.JButton();
        cekPengeluaranButton = new javax.swing.JButton();
        beriMakanButton = new javax.swing.JButton();
        beriVaksinButton = new javax.swing.JButton();
        beriObatButton = new javax.swing.JButton();
        cekKapasitasButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kambingSiapJual = new javax.swing.JLabel();
        sapiSiapJual = new javax.swing.JLabel();
        dombaSiapJual = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jumlahDomba = new javax.swing.JLabel();
        jumlahSapi = new javax.swing.JLabel();
        jumlahKambing = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelButuhTindakan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        totalPengeluaran = new javax.swing.JLabel();
        akunButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 190));
        jPanel1.setPreferredSize(new java.awt.Dimension(209, 500));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 23)); // NOI18N
        jLabel1.setText("VRINFARM");

        beliButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beliButton.setText("BELI");
        beliButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliButtonActionPerformed(evt);
            }
        });

        jualButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jualButton.setText("JUAL");
        jualButton.setMaximumSize(new java.awt.Dimension(146, 26));
        jualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualButtonActionPerformed(evt);
            }
        });

        breedButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        breedButton.setText("BREED");
        breedButton.setMaximumSize(new java.awt.Dimension(146, 26));
        breedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedButtonActionPerformed(evt);
            }
        });

        listHewanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        listHewanButton.setText("LIST HEWAN");
        listHewanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        listHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listHewanButtonActionPerformed(evt);
            }
        });

        listPegawaiButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        listPegawaiButton.setText("LIST PEGAWAI");
        listPegawaiButton.setMaximumSize(new java.awt.Dimension(146, 26));
        listPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPegawaiButtonActionPerformed(evt);
            }
        });

        gajiPegawaiButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        gajiPegawaiButton.setText("GAJI PEGAWAI");
        gajiPegawaiButton.setMaximumSize(new java.awt.Dimension(146, 26));
        gajiPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiPegawaiButtonActionPerformed(evt);
            }
        });

        cekPengeluaranButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekPengeluaranButton.setText("CEK PENGELUARAN");
        cekPengeluaranButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekPengeluaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPengeluaranButtonActionPerformed(evt);
            }
        });

        beriMakanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beriMakanButton.setText("BERI MAKAN");
        beriMakanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beriMakanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriMakanButtonActionPerformed(evt);
            }
        });

        beriVaksinButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beriVaksinButton.setText("BERI VAKSIN");
        beriVaksinButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beriVaksinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriVaksinButtonActionPerformed(evt);
            }
        });

        beriObatButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beriObatButton.setText("BERI OBAT");
        beriObatButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beriObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriObatButtonActionPerformed(evt);
            }
        });

        cekKapasitasButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekKapasitasButton.setText("CEK KAPASITAS");
        cekKapasitasButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekKapasitasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKapasitasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listHewanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listPegawaiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gajiPegawaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beriMakanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beriVaksinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beriObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekKapasitasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gajiPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekPengeluaranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beriMakanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beriVaksinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beriObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekKapasitasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 209, 500));

        jPanel2.setBackground(new java.awt.Color(221, 241, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(277, 199));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hewan Siap Jual");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Untitled design (8).png")); // NOI18N

        kambingSiapJual.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        kambingSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kambingSiapJual.setText("07");

        sapiSiapJual.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        sapiSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sapiSiapJual.setText("01");

        dombaSiapJual.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        dombaSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dombaSiapJual.setText("10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sapiSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(dombaSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(kambingSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sapiSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dombaSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kambingSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, -1));

        jPanel3.setBackground(new java.awt.Color(221, 241, 247));
        jPanel3.setPreferredSize(new java.awt.Dimension(277, 199));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Hewan");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Untitled design (8).png")); // NOI18N

        jumlahDomba.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jumlahDomba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahDomba.setText("99");

        jumlahSapi.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jumlahSapi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahSapi.setText("38");

        jumlahKambing.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jumlahKambing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahKambing.setText("56");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jumlahSapi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jumlahDomba, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jumlahKambing, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahSapi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahDomba, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahKambing, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255, 190));
        jPanel4.setPreferredSize(new java.awt.Dimension(277, 134));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hewan Butuh Tindakan");

        tabelButuhTindakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "MAKAN", "VAKSIN", "OBAT"
            }
        ));
        tabelButuhTindakan.setRowHeight(50);
        jScrollPane1.setViewportView(tabelButuhTindakan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 270, 170));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255, 190));
        jPanel5.setPreferredSize(new java.awt.Dimension(277, 134));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Pengeluaran");

        totalPengeluaran.setFont(new java.awt.Font("Comic Sans MS", 1, 34)); // NOI18N
        totalPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPengeluaran.setText("Rp 1.000.000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, 170));

        akunButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Untitled design (6).png")); // NOI18N
        akunButton.setBorder(null);
        akunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunButtonActionPerformed(evt);
            }
        });
        getContentPane().add(akunButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

        logoutButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Untitled design (7).png")); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\VrinFarm (1).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beliButtonActionPerformed

    private void jualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jualButtonActionPerformed

    private void breedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breedButtonActionPerformed

    private void listHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listHewanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listHewanButtonActionPerformed

    private void listPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPegawaiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPegawaiButtonActionPerformed

    private void gajiPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiPegawaiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajiPegawaiButtonActionPerformed

    private void cekPengeluaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPengeluaranButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekPengeluaranButtonActionPerformed

    private void beriMakanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriMakanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beriMakanButtonActionPerformed

    private void beriVaksinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriVaksinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beriVaksinButtonActionPerformed

    private void beriObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriObatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beriObatButtonActionPerformed

    private void cekKapasitasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekKapasitasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekKapasitasButtonActionPerformed

    private void akunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akunButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akunButton;
    private javax.swing.JButton beliButton;
    private javax.swing.JButton beriMakanButton;
    private javax.swing.JButton beriObatButton;
    private javax.swing.JButton beriVaksinButton;
    private javax.swing.JButton breedButton;
    private javax.swing.JButton cekKapasitasButton;
    private javax.swing.JButton cekPengeluaranButton;
    private javax.swing.JLabel dombaSiapJual;
    private javax.swing.JButton gajiPegawaiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jualButton;
    private javax.swing.JLabel jumlahDomba;
    private javax.swing.JLabel jumlahKambing;
    private javax.swing.JLabel jumlahSapi;
    private javax.swing.JLabel kambingSiapJual;
    private javax.swing.JButton listHewanButton;
    private javax.swing.JButton listPegawaiButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel sapiSiapJual;
    private javax.swing.JTable tabelButuhTindakan;
    private javax.swing.JLabel totalPengeluaran;
    // End of variables declaration//GEN-END:variables
}
